[package]
name = "bitvector_simd"
description = "bitvector implemented with Packed SIMD."
authors = ["Horasal"]
version = "0.3.0"
edition = "2018"
homepage = "https://github.com/horasal/bitvector_simd"
license = "MIT"
readme = "README.md"
repository = "https://github.com/horasal/bitvector_simd"
keywords = ["bitvector"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
packed_simd = "0.3.9"

[dev-dependencies]
criterion = "0.3"
bit-vec = "0.6"
bitvec = "0.22"

[[bench]]
name = "comparison"
harness = false
